In [27]:
import numpy as np
import json
import os
from scipy.spatial.transform import Rotation as R


In [5]:
base_path = "/home/lucas/Downloads/_out_sdrec"

In [6]:
idx = 0
camera_param_prefix = "camera_params_"
camera_param_ext = ".json"
camera_param_path = os.path.join(base_path, camera_param_prefix + str(idx).zfill(4)  + camera_param_ext)
with open(camera_param_path, 'r') as file:
    camera_param = json.load(file)

In [7]:
camera_param

{'cameraAperture': [20.954999923706055, 15.290800094604492],
 'cameraApertureOffset': [0.0, 0.0],
 'cameraFisheyeLensP': [],
 'cameraFisheyeLensS': [],
 'cameraFisheyeMaxFOV': 0.0,
 'cameraFisheyeNominalHeight': 0,
 'cameraFisheyeNominalWidth': 0,
 'cameraFisheyeOpticalCentre': [0.0, 0.0],
 'cameraFisheyePolynomial': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 'cameraFocalLength': 24.0,
 'cameraFocusDistance': 400.0,
 'cameraFStop': 0.0,
 'cameraModel': 'pinhole',
 'cameraNearFar': [1.0, 1000000.0],
 'cameraProjection': [2.2906228624246854,
  0.0,
  0.0,
  0.0,
  0.0,
  2.2906228624246854,
  0.0,
  0.0,
  0.0,
  0.0,
  1.000001000001e-06,
  -1.0,
  0.0,
  0.0,
  1.000001000001,
  0.0],
 'cameraViewTransform': [0.0047262735847906495,
  -2.2204212493251523e-16,
  0.9999888311066287,
  0.0,
  0.9999888311066287,
  1.0494435509024512e-18,
  -0.0047262735847906495,
  0.0,
  0.0,
  1.0,
  2.220446049250313e-16,
  -0.0,
  -11.941387335661105,
  -40.316699981689446,
  -24.576236738532632,
  1.0],
 'meter

In [22]:
camera_pose = camera_param['cameraViewTransform']
# camera_pose = np.linalg.inv(np.asarray(camera_pose).reshape(4, 4))
camera_pose = np.asarray(camera_pose).reshape(4, 4).T

In [24]:
camera_pose = np.linalg.inv(camera_pose)

In [25]:
translation = camera_pose[:3, -1]
rotation = camera_pose[:3, :3]

In [32]:
rotation

array([[ 4.72627358e-03, -2.22042125e-16,  9.99988831e-01],
       [ 9.99988831e-01,  1.04944355e-18, -4.72627358e-03],
       [ 0.00000000e+00,  1.00000000e+00,  2.22044605e-16]])

In [26]:
translation

array([24.63240051, 11.82509995, 40.31669998])

In [28]:
quat = R.from_matrix(rotation).as_quat()

In [29]:
quat

array([0.50118018, 0.49881703, 0.49881703, 0.50118018])